version: "2"

volumes:
    db:
        driver: local

services:
  bookstack:
    image: linuxserver/bookstack:v0.29.3-ls101
    container_name: bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - ${DOCKER_CONFIG_DIR}/bookstack/bookstack/config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DOCKER_CONFIG_DIR}/bookstack/bookstack_db/config:/config
    restart: unless-stopped
