version: "2"

services:

  server:
    image: gitea/gitea:latest
    container_name: gitea_server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    networks:
      - t2_proxy
    volumes:
      - ${DOCKER_CONFIG_DIR}/gitea/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
       - "3000:3000"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gitea-rtr.entrypoints=https"
      - "traefik.http.routers.gitea-rtr.rule=Host(`gitea.$DOMAINNAME`)"
      - "traefik.http.routers.gitea-rtr.tls=true"
      ## HTTP Services
      - "traefik.http.routers.gitea-rtr.service=gitea-svc"
      - "traefik.http.services.gitea-svc.loadbalancer.server.port=3000"


  db:
    image: mysql:5.7
    container_name: gitea_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - t2_proxy
    volumes:
      - ${DOCKER_CONFIG_DIR}/gitea/mysql:/var/lib/mysql


########################### NETWORKS

networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge