version: "2"

services:

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    volumes:
      - ${DOCKER_CONFIG_DIR}/jellyfin:/config
      - ${MEDIA_DIR}/plex:/data
    ports:
      - 8096:8096
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jellyfin-rtr.entrypoints=https"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.$DOMAINNAME`)"
      - "traefik.http.routers.jellyfin-rtr.tls=true"
      ## HTTP Services
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"


  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: always
    ports:
      - "9091:9091"
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      #- OPENVPN_USERNAME=${OPENVPN_USERNAME}
      #- OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - NORDVPN_COUNTRY=${NORDVPN_COUNTRY}
      - NORDVPN_PROTOCOL=${NORDVPN_PROTOCOL}
      - NORDVPN_CATEGORY=${NORDVPN_CATEGORY}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.100.0/24
      - CREATE_TUN_DEVICE=true
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - dns=1.1.1.1
      - TRANSMISSION_ALT_SPEED_DOWN=50
      - TRANSMISSION_ALT_SPEED_ENABLED=false
      - TRANSMISSION_ALT_SPEED_TIME_BEGIN=300
      - TRANSMISSION_ALT_SPEED_TIME_DAY=127
      - TRANSMISSION_ALT_SPEED_TIME_ENABLED=true
      - TRANSMISSION_ALT_SPEED_TIME_END=1320
      - TRANSMISSION_ALT_SPEED_UP=50
    volumes:
      - ${MEDIA_DIR}:/data
      - ${DOCKER_CONFIG_DIR}/transmission/credentials.txt:/config/openvpn-credentials.txt
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN

#########################################################

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/data

############################################################

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/radarr:/config
      - ${MEDIA_DIR}:/data

###########################################################################

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/jackett:/config
      - ${MEDIA_DIR}/downloads:/downloads
    ports:
      - "9117:9117"

###########################################################################

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/bazarr:/config
      - ${MEDIA_DIR}:/data
    ports:
      - 6767:6767
    restart: unless-stopped



########################### NETWORKS

networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge